/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    `java-library`
}

repositories {
    mavenCentral()
    maven {
        name = "spigotmc-repo"
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots")
    }
}

dependencies {
    api(libs.xseries)
    api(libs.annotations)
    compileOnly(libs.spigot.api)
}

description = "core"
